name: Build Android

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/android-build.yml'
      - 'apps/example-native/android/**'
      - 'nitrogen/generated/shared/**'
      - 'nitrogen/generated/android/**'
      - 'cpp/**'
      - 'android/**'
      - '**/yarn.lock'
      - '**/react-native.config.js'
      - '**/nitro.json'
  pull_request:
    paths:
      - '.github/workflows/android-build.yml'
      - 'apps/example-native/android/**'
      - '**/nitrogen/generated/shared/**'
      - '**/nitrogen/generated/android/**'
      - 'cpp/**'
      - 'android/**'
      - '**/yarn.lock'
      - '**/react-native.config.js'
      - '**/nitro.json'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Android Example App (${{ matrix.arch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [new, old]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn install

      - name: Disable new architecture in gradle.properties
        if: matrix.arch == 'old'
        run: sed -i "s/newArchEnabled=true/newArchEnabled=false/g" apps/example-native/android/gradle.properties

      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('apps/example-native/android/**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Gradle build
        working-directory: apps/example-native/android
        run: ./gradlew assembleDebug --no-daemon --build-cache

      - name: Stop Gradle daemon
        working-directory: apps/example-native/android
        run: ./gradlew --stop
