name: Build iOS

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ios-build.yml'
      - 'apps/example-native/ios/**'
      - 'apps/example-native/Gemfile'
      - 'apps/example-native/Gemfile.lock'
      - '**/nitrogen/generated/shared/**'
      - '**/nitrogen/generated/ios/**'
      - 'cpp/**'
      - 'ios/**'
      - '**/Podfile.lock'
      - '**/yarn.lock'
      - '**/*.podspec'
      - '**/react-native.config.js'
      - '**/nitro.json'
  pull_request:
    paths:
      - '.github/workflows/ios-build.yml'
      - 'apps/example-native/ios/**'
      - 'apps/example-native/Gemfile'
      - 'apps/example-native/Gemfile.lock'
      - '**/nitrogen/generated/shared/**'
      - '**/nitrogen/generated/ios/**'
      - 'cpp/**'
      - 'ios/**'
      - '**/Podfile.lock'
      - '**/yarn.lock'
      - '**/*.podspec'
      - '**/react-native.config.js'
      - '**/nitro.json'
  workflow_dispatch:

env:
  USE_CCACHE: 1

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build iOS Example App (${{ matrix.arch }})
    runs-on: macOS-15
    strategy:
      fail-fast: false
      matrix:
        arch: [new, old]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4

      - name: Install dependencies
        run: yarn install

      - name: Disable new architecture in Podfile
        if: matrix.arch == 'old'
        run: sed -i "" "s/ENV\['RCT_NEW_ARCH_ENABLED'\] = '1'/ENV['RCT_NEW_ARCH_ENABLED'] = '0'/g" apps/example-native/ios/Podfile

      - name: Setup Ruby (bundle)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: apps/example-native/ios

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ~/.cocoapods/repos
            apps/example-native/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('apps/example-native/ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Pods
        working-directory: apps/example-native/ios
        run: pod install

      - name: Build App
        working-directory: apps/example-native/ios
        run: |
          set -o pipefail && xcodebuild \
            CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ \
            -derivedDataPath build -UseModernBuildSystem=YES \
            -workspace AudioBrowserExample.xcworkspace \
            -scheme AudioBrowserExample \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 16' \
            build \
            CODE_SIGNING_ALLOWED=NO | xcpretty
